/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Principal;

import Entidades.Vector;
import Utilidades.Util;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;

/**
 *
 * @author edwinmanzano
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        viewPort = new ViewPort();
        canvas = viewPort.getCanvas();
        
        initComponents();
        
        JViewPort.add(viewPort);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JViewPort = new javax.swing.JPanel();
        btnLimpiar = new javax.swing.JButton();
        BtnPintar2Colores = new javax.swing.JButton();
        btnInterpolarColores = new javax.swing.JButton();
        btnPintarPixel = new javax.swing.JButton();
        btnSecuenciaPixceles = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gráficos 2D - 6626");
        setPreferredSize(new java.awt.Dimension(920, 620));

        JViewPort.setAlignmentX(0.0F);
        JViewPort.setAlignmentY(0.0F);
        JViewPort.setMaximumSize(new java.awt.Dimension(700, 500));
        JViewPort.setMinimumSize(new java.awt.Dimension(700, 500));
        JViewPort.setPreferredSize(new java.awt.Dimension(700, 500));

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        BtnPintar2Colores.setText("Pintar 2 Colores");
        BtnPintar2Colores.setPreferredSize(new java.awt.Dimension(157, 29));
        BtnPintar2Colores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPintar2ColoresActionPerformed(evt);
            }
        });

        btnInterpolarColores.setText("Interpolar Colores");
        btnInterpolarColores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInterpolarColoresActionPerformed(evt);
            }
        });

        btnPintarPixel.setText("Encender Pixcel");
        btnPintarPixel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPintarPixelActionPerformed(evt);
            }
        });

        btnSecuenciaPixceles.setText("Secuencia de Pixceles");
        btnSecuenciaPixceles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSecuenciaPixcelesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JViewPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnSecuenciaPixceles, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                            .addComponent(btnPintarPixel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnInterpolarColores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnPintar2Colores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(BtnPintar2Colores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnInterpolarColores)
                        .addGap(18, 18, 18)
                        .addComponent(btnPintarPixel)
                        .addGap(18, 18, 18)
                        .addComponent(btnSecuenciaPixceles))
                    .addComponent(JViewPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnPintar2ColoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPintar2ColoresActionPerformed
        for(int i = 0; i<700; i++){
            for(int j = 0; j < 500; j++){
                if(i<350)
                    viewPort.pintarPixelCanvas(i, j, Color.RED, canvas);
                else
                    viewPort.pintarPixelCanvas(i, j, Color.BLUE, canvas);
            }
        }
        viewPort.Pintar(canvas);
    }//GEN-LAST:event_BtnPintar2ColoresActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        viewPort.limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnInterpolarColoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInterpolarColoresActionPerformed
        for(int i = 0; i < 700; i++){
            for(int j = 0; j < 500; j++){
                int c1 = (int) Util.interpolar2Puntos(i, 0.0, 255.0, 699.0, 0.0);
                int c2 = (int) Util.interpolar2Puntos(i, 0.0, 0.0, 699.0, 0.0);
                int c3 = (int) Util.interpolar2Puntos(i, 0.0, 0.0, 699.0, 255.0);
                Color color = new Color (c1, c2, c3);
                viewPort.pintarPixelCanvas(i, j, color, canvas);
            }
        }
        viewPort.Pintar(canvas);
    }//GEN-LAST:event_btnInterpolarColoresActionPerformed

    private void btnPintarPixelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPintarPixelActionPerformed
        Vector v = new Vector ();
        
        v.setX0(2.0);
        v.setY0(3.0);
        v.setColor(Color.RED);
        
        v.encender(canvas);
        
        viewPort.Pintar(canvas);
    }//GEN-LAST:event_btnPintarPixelActionPerformed

    private void btnSecuenciaPixcelesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSecuenciaPixcelesActionPerformed
        Vector v = new Vector ();
        
        double x = -1.0;
        
        do{
            v.setX0(x);
            v.setY0(x);
            v.setColor(Color.RED);

            v.encender(canvas);
            
            x += 0.05;
        }while(x<=3);
        
        viewPort.Pintar(canvas);
    }//GEN-LAST:event_btnSecuenciaPixcelesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmPrincipal vP = new FrmPrincipal();
                
                Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
                
                Dimension vS = vP.getSize();
                
                vP.setLocation((d.height - vS.height)/2, (d.width - vS.width)/2);
                
                vP.setVisible(true);
            }
        });
    }

    BufferedImage canvas;
    ViewPort viewPort;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnPintar2Colores;
    private javax.swing.JPanel JViewPort;
    private javax.swing.JButton btnInterpolarColores;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnPintarPixel;
    private javax.swing.JButton btnSecuenciaPixceles;
    // End of variables declaration//GEN-END:variables
}
